// Datos completos de los 160 componentes del proyecto
// Esta data será usada para hacer seed de la tabla components

export const componentsData = [
  // ==========================================
  // ANIMATIONS - BACKGROUNDS (30 componentes)
  // ==========================================
  {
    name: 'Aurora',
    displayName: 'Aurora Background',
    slug: 'aurora',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Beautiful aurora borealis gradient background with smooth animations',
    icon: '🌌',
    tags: ['background', 'gradient', 'animation', 'aurora'],
    componentPath: 'components/animations/backgrounds/Aurora.tsx',
    variantId: 1,
  },
  {
    name: 'Balatro',
    displayName: 'Balatro Background',
    slug: 'balatro',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Card-game inspired animated background effect',
    icon: '🃏',
    tags: ['background', 'cards', 'animation'],
    componentPath: 'components/animations/backgrounds/Balatro.tsx',
    variantId: 1,
  },
  {
    name: 'Ballpit',
    displayName: 'Ball Pit Background',
    slug: 'ballpit',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Physics-based animated ball pit background',
    icon: '⚽',
    tags: ['background', 'physics', 'animation', 'balls'],
    componentPath: 'components/animations/backgrounds/Ballpit.tsx',
    variantId: 1,
  },
  {
    name: 'Beams',
    displayName: 'Light Beams',
    slug: 'beams',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Animated light beams background effect',
    icon: '✨',
    tags: ['background', 'light', 'beams', 'animation'],
    componentPath: 'components/animations/backgrounds/Beams.tsx',
    variantId: 1,
  },
  {
    name: 'DarkVeil',
    displayName: 'Dark Veil',
    slug: 'dark-veil',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Dark gradient veil overlay background',
    icon: '🌑',
    tags: ['background', 'dark', 'gradient', 'overlay'],
    componentPath: 'components/animations/backgrounds/DarkVeil.tsx',
    variantId: 1,
  },
  {
    name: 'Dither',
    displayName: 'Dithered Background',
    slug: 'dither',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Retro dithered pattern background effect',
    icon: '▓',
    tags: ['background', 'dither', 'retro', 'pattern'],
    componentPath: 'components/animations/backgrounds/Dither.tsx',
    variantId: 1,
  },
  {
    name: 'DotGrid',
    displayName: 'Dot Grid Background',
    slug: 'dot-grid',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Animated dot grid pattern background',
    icon: '⋮',
    tags: ['background', 'dots', 'grid', 'pattern'],
    componentPath: 'components/animations/backgrounds/DotGrid.tsx',
    variantId: 1,
  },
  {
    name: 'FaultyTerminal',
    displayName: 'Faulty Terminal',
    slug: 'faulty-terminal',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Glitchy terminal-style background effect',
    icon: '💻',
    tags: ['background', 'terminal', 'glitch', 'tech'],
    componentPath: 'components/animations/backgrounds/FaultyTerminal.tsx',
    variantId: 1,
  },
  {
    name: 'Galaxy',
    displayName: 'Galaxy Background',
    slug: 'galaxy',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Stunning galaxy starfield background with depth',
    icon: '🌌',
    tags: ['background', 'space', 'stars', 'galaxy'],
    componentPath: 'components/animations/backgrounds/Galaxy.tsx',
    variantId: 1,
  },
  {
    name: 'GradientBlinds',
    displayName: 'Gradient Blinds',
    slug: 'gradient-blinds',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Animated gradient blinds transition effect',
    icon: '🎨',
    tags: ['background', 'gradient', 'animation', 'transition'],
    componentPath: 'components/animations/backgrounds/GradientBlinds.tsx',
    variantId: 1,
  },
  {
    name: 'GridDistortion',
    displayName: 'Grid Distortion',
    slug: 'grid-distortion',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Warped grid background with distortion effect',
    icon: '🌀',
    tags: ['background', 'grid', 'distortion', 'warp'],
    componentPath: 'components/animations/backgrounds/GridDistortion.tsx',
    variantId: 1,
  },
  {
    name: 'GridMotion',
    displayName: 'Grid Motion',
    slug: 'grid-motion',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Animated moving grid background',
    icon: '📐',
    tags: ['background', 'grid', 'motion', 'animation'],
    componentPath: 'components/animations/backgrounds/GridMotion.tsx',
    variantId: 1,
  },
  {
    name: 'Hyperspeed',
    displayName: 'Hyperspeed',
    slug: 'hyperspeed',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Fast-moving starfield hyperspeed effect',
    icon: '🚀',
    tags: ['background', 'speed', 'stars', 'motion'],
    componentPath: 'components/animations/backgrounds/Hyperspeed.tsx',
    variantId: 1,
  },
  {
    name: 'Iridescence',
    displayName: 'Iridescence',
    slug: 'iridescence',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Shimmering iridescent color background',
    icon: '🦋',
    tags: ['background', 'iridescent', 'shimmer', 'color'],
    componentPath: 'components/animations/backgrounds/Iridescence.tsx',
    variantId: 1,
  },
  {
    name: 'LetterGlitch',
    displayName: 'Letter Glitch',
    slug: 'letter-glitch',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Glitchy text characters background',
    icon: '🔤',
    tags: ['background', 'glitch', 'text', 'letters'],
    componentPath: 'components/animations/backgrounds/LetterGlitch.tsx',
    variantId: 1,
  },
  {
    name: 'Lightning',
    displayName: 'Lightning',
    slug: 'lightning',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Electric lightning bolt background effect',
    icon: '⚡',
    tags: ['background', 'lightning', 'electric', 'energy'],
    componentPath: 'components/animations/backgrounds/Lightning.tsx',
    variantId: 1,
  },
  {
    name: 'LightRays',
    displayName: 'Light Rays',
    slug: 'light-rays',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Radial light rays background effect',
    icon: '☀️',
    tags: ['background', 'light', 'rays', 'radial'],
    componentPath: 'components/animations/backgrounds/LightRays.tsx',
    variantId: 1,
  },
  {
    name: 'LiquidChrome',
    displayName: 'Liquid Chrome',
    slug: 'liquid-chrome',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Flowing liquid chrome metallic effect',
    icon: '💧',
    tags: ['background', 'liquid', 'chrome', 'metallic'],
    componentPath: 'components/animations/backgrounds/LiquidChrome.tsx',
    variantId: 1,
  },
  {
    name: 'LiquidEther',
    displayName: 'Liquid Ether',
    slug: 'liquid-ether',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Ethereal flowing liquid background',
    icon: '🌊',
    tags: ['background', 'liquid', 'ether', 'flow'],
    componentPath: 'components/animations/backgrounds/LiquidEther.tsx',
    variantId: 1,
  },
  {
    name: 'Orb',
    displayName: 'Orb',
    slug: 'orb',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Glowing orb gradient background',
    icon: '🔮',
    tags: ['background', 'orb', 'glow', 'gradient'],
    componentPath: 'components/animations/backgrounds/Orb.tsx',
    variantId: 1,
  },
  {
    name: 'Particles',
    displayName: 'Particles',
    slug: 'particles',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Floating particle system background',
    icon: '✨',
    tags: ['background', 'particles', 'floating', 'animation'],
    componentPath: 'components/animations/backgrounds/Particles.tsx',
    variantId: 1,
  },
  {
    name: 'PixelBlast',
    displayName: 'Pixel Blast',
    slug: 'pixel-blast',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Explosive pixel animation background',
    icon: '💥',
    tags: ['background', 'pixels', 'explosion', 'animation'],
    componentPath: 'components/animations/backgrounds/PixelBlast.tsx',
    variantId: 1,
  },
  {
    name: 'Plasma',
    displayName: 'Plasma',
    slug: 'plasma',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Animated plasma energy background',
    icon: '🔥',
    tags: ['background', 'plasma', 'energy', 'animation'],
    componentPath: 'components/animations/backgrounds/Plasma.tsx',
    variantId: 1,
  },
  {
    name: 'Prism',
    displayName: 'Prism',
    slug: 'prism',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Rainbow prism refraction background',
    icon: '🌈',
    tags: ['background', 'prism', 'rainbow', 'light'],
    componentPath: 'components/animations/backgrounds/Prism.tsx',
    variantId: 1,
  },
  {
    name: 'PrismaticBurst',
    displayName: 'Prismatic Burst',
    slug: 'prismatic-burst',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Bursting prismatic color explosion',
    icon: '💫',
    tags: ['background', 'prismatic', 'burst', 'colors'],
    componentPath: 'components/animations/backgrounds/PrismaticBurst.tsx',
    variantId: 1,
  },
  {
    name: 'RippleGrid',
    displayName: 'Ripple Grid',
    slug: 'ripple-grid',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Wave ripple effect on grid background',
    icon: '〰️',
    tags: ['background', 'ripple', 'grid', 'wave'],
    componentPath: 'components/animations/backgrounds/RippleGrid.tsx',
    variantId: 1,
  },
  {
    name: 'Silk',
    displayName: 'Silk',
    slug: 'silk',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Smooth flowing silk fabric background',
    icon: '🎀',
    tags: ['background', 'silk', 'fabric', 'smooth'],
    componentPath: 'components/animations/backgrounds/Silk.tsx',
    variantId: 1,
  },
  {
    name: 'Squares',
    displayName: 'Animated Squares',
    slug: 'squares',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Animated geometric squares pattern',
    icon: '◼️',
    tags: ['background', 'squares', 'geometric', 'pattern'],
    componentPath: 'components/animations/backgrounds/Squares.tsx',
    variantId: 1,
  },
  {
    name: 'Threads',
    displayName: 'Threads',
    slug: 'threads',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Interconnected thread lines background',
    icon: '🧵',
    tags: ['background', 'threads', 'lines', 'connections'],
    componentPath: 'components/animations/backgrounds/Threads.tsx',
    variantId: 1,
  },
  {
    name: 'Waves',
    displayName: 'Waves',
    slug: 'waves',
    category: 'ANIMATIONS',
    subcategory: 'backgrounds',
    type: 'background',
    description: 'Flowing wave pattern background',
    icon: '🌊',
    tags: ['background', 'waves', 'flow', 'pattern'],
    componentPath: 'components/animations/backgrounds/Waves.tsx',
    variantId: 1,
  },

  // ==========================================
  // ANIMATIONS - INTERACTIVE (36 componentes)
  // ==========================================
  {
    name: 'AnimatedList',
    displayName: 'Animated List',
    slug: 'animated-list',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'List with smooth enter/exit animations',
    icon: '📋',
    tags: ['list', 'animation', 'interactive', 'stagger'],
    componentPath: 'components/animations/interactive/AnimatedList.tsx',
    variantId: 1,
  },
  {
    name: 'BounceCards',
    displayName: 'Bounce Cards',
    slug: 'bounce-cards',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Cards with bouncy hover animations',
    icon: '🎴',
    tags: ['cards', 'bounce', 'interactive', 'hover'],
    componentPath: 'components/animations/interactive/BounceCards.tsx',
    variantId: 1,
  },
  {
    name: 'BubbleMenu',
    displayName: 'Bubble Menu',
    slug: 'bubble-menu',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'header',
    description: 'Floating bubble menu with smooth transitions',
    icon: '🫧',
    tags: ['menu', 'bubble', 'navigation', 'floating'],
    componentPath: 'components/animations/interactive/BubbleMenu.tsx',
    variantId: 1,
  },
  {
    name: 'CardNav',
    displayName: 'Card Navigation',
    slug: 'card-nav',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'header',
    description: 'Card-based navigation menu',
    icon: '🎯',
    tags: ['navigation', 'cards', 'menu', 'interactive'],
    componentPath: 'components/animations/interactive/CardNav.tsx',
    variantId: 1,
  },
  {
    name: 'CardSwap',
    displayName: 'Card Swap',
    slug: 'card-swap',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Swappable cards with flip animation',
    icon: '🔄',
    tags: ['cards', 'swap', 'flip', 'interactive'],
    componentPath: 'components/animations/interactive/CardSwap.tsx',
    variantId: 1,
  },
  {
    name: 'Carousel',
    displayName: 'Carousel',
    slug: 'carousel',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'gallery',
    description: 'Smooth image carousel with navigation',
    icon: '🎠',
    tags: ['carousel', 'slider', 'gallery', 'images'],
    componentPath: 'components/animations/interactive/Carousel.tsx',
    variantId: 1,
  },
  {
    name: 'ChromaGrid',
    displayName: 'Chroma Grid',
    slug: 'chroma-grid',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Colorful interactive grid layout',
    icon: '🎨',
    tags: ['grid', 'colors', 'interactive', 'chroma'],
    componentPath: 'components/animations/interactive/ChromaGrid.tsx',
    variantId: 1,
  },
  {
    name: 'CircularGallery',
    displayName: 'Circular Gallery',
    slug: 'circular-gallery',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'gallery',
    description: 'Images arranged in circular layout',
    icon: '⭕',
    tags: ['gallery', 'circular', 'images', 'layout'],
    componentPath: 'components/animations/interactive/CircularGallery.tsx',
    variantId: 1,
  },
  {
    name: 'Counter',
    displayName: 'Animated Counter',
    slug: 'counter',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'stats',
    description: 'Number counter with smooth animation',
    icon: '🔢',
    tags: ['counter', 'numbers', 'stats', 'animation'],
    componentPath: 'components/animations/interactive/Counter.tsx',
    variantId: 1,
  },
  {
    name: 'DecayCard',
    displayName: 'Decay Card',
    slug: 'decay-card',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Card with particle decay effect',
    icon: '💨',
    tags: ['card', 'decay', 'particles', 'effect'],
    componentPath: 'components/animations/interactive/DecayCard.tsx',
    variantId: 1,
  },
  {
    name: 'Dock',
    displayName: 'Dock',
    slug: 'dock',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'header',
    description: 'MacOS-style dock navigation',
    icon: '⚓',
    tags: ['dock', 'navigation', 'macos', 'menu'],
    componentPath: 'components/animations/interactive/Dock.tsx',
    variantId: 1,
  },
  {
    name: 'DomeGallery',
    displayName: 'Dome Gallery',
    slug: 'dome-gallery',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'gallery',
    description: '3D dome-shaped image gallery',
    icon: '🏛️',
    tags: ['gallery', '3d', 'dome', 'images'],
    componentPath: 'components/animations/interactive/DomeGallery.tsx',
    variantId: 1,
  },
  {
    name: 'ElasticSlider',
    displayName: 'Elastic Slider',
    slug: 'elastic-slider',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'gallery',
    description: 'Slider with elastic physics animations',
    icon: '🎚️',
    tags: ['slider', 'elastic', 'physics', 'gallery'],
    componentPath: 'components/animations/interactive/ElasticSlider.tsx',
    variantId: 1,
  },
  {
    name: 'FlowingMenu',
    displayName: 'Flowing Menu',
    slug: 'flowing-menu',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'header',
    description: 'Menu with fluid flowing animations',
    icon: '〰️',
    tags: ['menu', 'flowing', 'navigation', 'fluid'],
    componentPath: 'components/animations/interactive/FlowingMenu.tsx',
    variantId: 1,
  },
  {
    name: 'FluidGlass',
    displayName: 'Fluid Glass',
    slug: 'fluid-glass',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Glassmorphism with fluid animations',
    icon: '💎',
    tags: ['glass', 'fluid', 'glassmorphism', 'effect'],
    componentPath: 'components/animations/interactive/FluidGlass.tsx',
    variantId: 1,
  },
  {
    name: 'FlyingPosters',
    displayName: 'Flying Posters',
    slug: 'flying-posters',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'gallery',
    description: 'Floating poster gallery with 3D effect',
    icon: '🎪',
    tags: ['posters', 'flying', '3d', 'gallery'],
    componentPath: 'components/animations/interactive/FlyingPosters.tsx',
    variantId: 1,
  },
  {
    name: 'Folder',
    displayName: 'Animated Folder',
    slug: 'folder',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Interactive folder with expand animation',
    icon: '📁',
    tags: ['folder', 'expand', 'interactive', 'animation'],
    componentPath: 'components/animations/interactive/Folder.tsx',
    variantId: 1,
  },
  {
    name: 'GlassIcons',
    displayName: 'Glass Icons',
    slug: 'glass-icons',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Icon grid with glassmorphism effect',
    icon: '🔷',
    tags: ['icons', 'glass', 'glassmorphism', 'grid'],
    componentPath: 'components/animations/interactive/GlassIcons.tsx',
    variantId: 1,
  },
  {
    name: 'GlassSurface',
    displayName: 'Glass Surface',
    slug: 'glass-surface',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Interactive glass surface effect',
    icon: '🪟',
    tags: ['glass', 'surface', 'interactive', 'effect'],
    componentPath: 'components/animations/interactive/GlassSurface.tsx',
    variantId: 1,
  },
  {
    name: 'GooeyNav',
    displayName: 'Gooey Navigation',
    slug: 'gooey-nav',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'header',
    description: 'Navigation with gooey morph effect',
    icon: '🫗',
    tags: ['navigation', 'gooey', 'morph', 'menu'],
    componentPath: 'components/animations/interactive/GooeyNav.tsx',
    variantId: 1,
  },
  {
    name: 'InfiniteMenu',
    displayName: 'Infinite Menu',
    slug: 'infinite-menu',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'header',
    description: 'Infinite scrolling menu carousel',
    icon: '∞',
    tags: ['menu', 'infinite', 'scroll', 'navigation'],
    componentPath: 'components/animations/interactive/InfiniteMenu.tsx',
    variantId: 1,
  },
  {
    name: 'InfiniteScroll',
    displayName: 'Infinite Scroll',
    slug: 'infinite-scroll',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Smooth infinite scrolling content',
    icon: '📜',
    tags: ['scroll', 'infinite', 'content', 'animation'],
    componentPath: 'components/animations/interactive/InfiniteScroll.tsx',
    variantId: 1,
  },
  {
    name: 'Lanyard',
    displayName: 'Lanyard',
    slug: 'lanyard',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Hanging card lanyard effect',
    icon: '🎫',
    tags: ['lanyard', 'card', 'hanging', 'effect'],
    componentPath: 'components/animations/interactive/Lanyard.tsx',
    variantId: 1,
  },
  {
    name: 'MagicBento',
    displayName: 'Magic Bento',
    slug: 'magic-bento',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Bento grid with magical animations',
    icon: '🍱',
    tags: ['bento', 'grid', 'magic', 'layout'],
    componentPath: 'components/animations/interactive/MagicBento.tsx',
    variantId: 1,
  },
  {
    name: 'Masonry',
    displayName: 'Masonry Grid',
    slug: 'masonry',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'gallery',
    description: 'Pinterest-style masonry layout',
    icon: '🧱',
    tags: ['masonry', 'grid', 'layout', 'gallery'],
    componentPath: 'components/animations/interactive/Masonry.tsx',
    variantId: 1,
  },
  {
    name: 'ModelViewer',
    displayName: '3D Model Viewer',
    slug: 'model-viewer',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'gallery',
    description: 'Interactive 3D model viewer',
    icon: '🎲',
    tags: ['3d', 'model', 'viewer', 'interactive'],
    componentPath: 'components/animations/interactive/ModelViewer.tsx',
    variantId: 1,
  },
  {
    name: 'PillNav',
    displayName: 'Pill Navigation',
    slug: 'pill-nav',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'header',
    description: 'Pill-shaped navigation menu',
    icon: '💊',
    tags: ['navigation', 'pill', 'menu', 'modern'],
    componentPath: 'components/animations/interactive/PillNav.tsx',
    variantId: 1,
  },
  {
    name: 'PixelCard',
    displayName: 'Pixel Card',
    slug: 'pixel-card',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Retro pixelated card effect',
    icon: '🎮',
    tags: ['card', 'pixel', 'retro', 'effect'],
    componentPath: 'components/animations/interactive/PixelCard.tsx',
    variantId: 1,
  },
  {
    name: 'ProfileCard',
    displayName: 'Profile Card',
    slug: 'profile-card',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'testimonials',
    description: 'Animated profile card component',
    icon: '👤',
    tags: ['profile', 'card', 'user', 'avatar'],
    componentPath: 'components/animations/interactive/ProfileCard.tsx',
    variantId: 1,
  },
  {
    name: 'RollingGallery',
    displayName: 'Rolling Gallery',
    slug: 'rolling-gallery',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'gallery',
    description: 'Gallery with rolling transition effect',
    icon: '🎡',
    tags: ['gallery', 'rolling', 'transition', 'images'],
    componentPath: 'components/animations/interactive/RollingGallery.tsx',
    variantId: 1,
  },
  {
    name: 'ScrollStack',
    displayName: 'Scroll Stack',
    slug: 'scroll-stack',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Stacked cards with scroll animations',
    icon: '📚',
    tags: ['scroll', 'stack', 'cards', 'animation'],
    componentPath: 'components/animations/interactive/ScrollStack.tsx',
    variantId: 1,
  },
  {
    name: 'SpotlightCard',
    displayName: 'Spotlight Card',
    slug: 'spotlight-card',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Card with spotlight hover effect',
    icon: '🔦',
    tags: ['card', 'spotlight', 'hover', 'effect'],
    componentPath: 'components/animations/interactive/SpotlightCard.tsx',
    variantId: 1,
  },
  {
    name: 'Stack',
    displayName: 'Stack',
    slug: 'stack',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Stackable card component',
    icon: '📇',
    tags: ['stack', 'cards', 'layered', 'interactive'],
    componentPath: 'components/animations/interactive/Stack.tsx',
    variantId: 1,
  },
  {
    name: 'StaggeredMenu',
    displayName: 'Staggered Menu',
    slug: 'staggered-menu',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'header',
    description: 'Menu with staggered animation',
    icon: '🎭',
    tags: ['menu', 'staggered', 'animation', 'navigation'],
    componentPath: 'components/animations/interactive/StaggeredMenu.tsx',
    variantId: 1,
  },
  {
    name: 'Stepper',
    displayName: 'Stepper',
    slug: 'stepper',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'form',
    description: 'Multi-step form with progress',
    icon: '👣',
    tags: ['stepper', 'form', 'steps', 'progress'],
    componentPath: 'components/animations/interactive/Stepper.tsx',
    variantId: 1,
  },
  {
    name: 'TiltedCard',
    displayName: 'Tilted Card',
    slug: 'tilted-card',
    category: 'ANIMATIONS',
    subcategory: 'interactive',
    type: 'features',
    description: 'Card with 3D tilt effect on hover',
    icon: '🎴',
    tags: ['card', 'tilt', '3d', 'hover'],
    componentPath: 'components/animations/interactive/TiltedCard.tsx',
    variantId: 1,
  },

  // ==========================================
  // ANIMATIONS - TEXT (24 componentes)
  // ==========================================
  {
    name: 'ASCIIText',
    displayName: 'ASCII Text',
    slug: 'ascii-text',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with ASCII art effect',
    icon: '⌨️',
    tags: ['text', 'ascii', 'retro', 'effect'],
    componentPath: 'components/animations/text/ASCIIText.tsx',
    variantId: 1,
  },
  {
    name: 'BlurText',
    displayName: 'Blur Text',
    slug: 'blur-text',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with animated blur effect',
    icon: '🌫️',
    tags: ['text', 'blur', 'animation', 'effect'],
    componentPath: 'components/animations/text/BlurText.tsx',
    variantId: 1,
  },
  {
    name: 'CircularText',
    displayName: 'Circular Text',
    slug: 'circular-text',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text arranged in circular path',
    icon: '🔄',
    tags: ['text', 'circular', 'path', 'animation'],
    componentPath: 'components/animations/text/CircularText.tsx',
    variantId: 1,
  },
  {
    name: 'CountUp',
    displayName: 'Count Up',
    slug: 'count-up',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'stats',
    description: 'Animated counting number text',
    icon: '🔢',
    tags: ['text', 'counter', 'numbers', 'animation'],
    componentPath: 'components/animations/text/CountUp.tsx',
    variantId: 1,
  },
  {
    name: 'CurvedLoop',
    displayName: 'Curved Loop',
    slug: 'curved-loop',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text looping on curved path',
    icon: '➰',
    tags: ['text', 'curve', 'loop', 'animation'],
    componentPath: 'components/animations/text/CurvedLoop.tsx',
    variantId: 1,
  },
  {
    name: 'DecryptedText',
    displayName: 'Decrypted Text',
    slug: 'decrypted-text',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with decryption reveal effect',
    icon: '🔓',
    tags: ['text', 'decrypt', 'reveal', 'animation'],
    componentPath: 'components/animations/text/DecryptedText.tsx',
    variantId: 1,
  },
  {
    name: 'FallingText',
    displayName: 'Falling Text',
    slug: 'falling-text',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with falling animation',
    icon: '⬇️',
    tags: ['text', 'falling', 'gravity', 'animation'],
    componentPath: 'components/animations/text/FallingText.tsx',
    variantId: 1,
  },
  {
    name: 'FuzzyText',
    displayName: 'Fuzzy Text',
    slug: 'fuzzy-text',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with fuzzy distortion effect',
    icon: '〰️',
    tags: ['text', 'fuzzy', 'distortion', 'effect'],
    componentPath: 'components/animations/text/FuzzyText.tsx',
    variantId: 1,
  },
  {
    name: 'GlitchText',
    displayName: 'Glitch Text',
    slug: 'glitch-text',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with glitch animation effect',
    icon: '⚡',
    tags: ['text', 'glitch', 'digital', 'effect'],
    componentPath: 'components/animations/text/GlitchText.tsx',
    variantId: 1,
  },
  {
    name: 'GradientText',
    displayName: 'Gradient Text',
    slug: 'gradient-text',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with animated gradient colors',
    icon: '🌈',
    tags: ['text', 'gradient', 'colors', 'animation'],
    componentPath: 'components/animations/text/GradientText.tsx',
    variantId: 1,
  },
  {
    name: 'RotatingText',
    displayName: 'Rotating Text',
    slug: 'rotating-text',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with rotation animation',
    icon: '🔄',
    tags: ['text', 'rotate', 'spin', 'animation'],
    componentPath: 'components/animations/text/RotatingText.tsx',
    variantId: 1,
  },
  {
    name: 'ScrambledText',
    displayName: 'Scrambled Text',
    slug: 'scrambled-text',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with scramble reveal effect',
    icon: '🎲',
    tags: ['text', 'scramble', 'reveal', 'animation'],
    componentPath: 'components/animations/text/ScrambledText.tsx',
    variantId: 1,
  },
  {
    name: 'ScrollFloat',
    displayName: 'Scroll Float',
    slug: 'scroll-float',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text floating on scroll',
    icon: '☁️',
    tags: ['text', 'scroll', 'float', 'parallax'],
    componentPath: 'components/animations/text/ScrollFloat.tsx',
    variantId: 1,
  },
  {
    name: 'ScrollReveal',
    displayName: 'Scroll Reveal',
    slug: 'scroll-reveal',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text revealed on scroll',
    icon: '👁️',
    tags: ['text', 'scroll', 'reveal', 'animation'],
    componentPath: 'components/animations/text/ScrollReveal.tsx',
    variantId: 1,
  },
  {
    name: 'ScrollVelocity',
    displayName: 'Scroll Velocity',
    slug: 'scroll-velocity',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text affected by scroll velocity',
    icon: '⚡',
    tags: ['text', 'scroll', 'velocity', 'animation'],
    componentPath: 'components/animations/text/ScrollVelocity.tsx',
    variantId: 1,
  },
  {
    name: 'ShinyText',
    displayName: 'Shiny Text',
    slug: 'shiny-text',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with shiny shimmer effect',
    icon: '✨',
    tags: ['text', 'shiny', 'shimmer', 'effect'],
    componentPath: 'components/animations/text/ShinyText.tsx',
    variantId: 1,
  },
  {
    name: 'Shuffle',
    displayName: 'Shuffle Text',
    slug: 'shuffle',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with shuffle animation',
    icon: '🔀',
    tags: ['text', 'shuffle', 'random', 'animation'],
    componentPath: 'components/animations/text/Shuffle.tsx',
    variantId: 1,
  },
  {
    name: 'SplitText',
    displayName: 'Split Text',
    slug: 'split-text',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with split reveal animation',
    icon: '✂️',
    tags: ['text', 'split', 'reveal', 'animation'],
    componentPath: 'components/animations/text/SplitText.tsx',
    variantId: 1,
  },
  {
    name: 'TextCursor',
    displayName: 'Text Cursor',
    slug: 'text-cursor',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Typewriter cursor effect',
    icon: '|',
    tags: ['text', 'cursor', 'typewriter', 'animation'],
    componentPath: 'components/animations/text/TextCursor.tsx',
    variantId: 1,
  },
  {
    name: 'TextPressure',
    displayName: 'Text Pressure',
    slug: 'text-pressure',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with pressure-sensitive effect',
    icon: '👆',
    tags: ['text', 'pressure', 'interactive', 'effect'],
    componentPath: 'components/animations/text/TextPressure.tsx',
    variantId: 1,
  },
  {
    name: 'TextTrail',
    displayName: 'Text Trail',
    slug: 'text-trail',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with trailing effect',
    icon: '💫',
    tags: ['text', 'trail', 'motion', 'effect'],
    componentPath: 'components/animations/text/TextTrail.tsx',
    variantId: 1,
  },
  {
    name: 'TextType',
    displayName: 'Text Type',
    slug: 'text-type',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Typewriter text animation',
    icon: '⌨️',
    tags: ['text', 'typewriter', 'typing', 'animation'],
    componentPath: 'components/animations/text/TextType.tsx',
    variantId: 1,
  },
  {
    name: 'TrueFocus',
    displayName: 'True Focus',
    slug: 'true-focus',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with focus blur effect',
    icon: '🎯',
    tags: ['text', 'focus', 'blur', 'effect'],
    componentPath: 'components/animations/text/TrueFocus.tsx',
    variantId: 1,
  },
  {
    name: 'VariableProximity',
    displayName: 'Variable Proximity',
    slug: 'variable-proximity',
    category: 'ANIMATIONS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with proximity-based size variation',
    icon: '📏',
    tags: ['text', 'proximity', 'variable', 'interactive'],
    componentPath: 'components/animations/text/VariableProximity.tsx',
    variantId: 1,
  },

  // ==========================================
  // ANIMATIONS - TRANSITIONS (25 componentes)
  // ==========================================
  {
    name: 'AnimatedContent',
    displayName: 'Animated Content',
    slug: 'animated-content',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Content with smooth enter/exit animations',
    icon: '🎬',
    tags: ['transition', 'content', 'animation', 'smooth'],
    componentPath: 'components/animations/transitions/AnimatedContent.tsx',
    variantId: 1,
  },
  {
    name: 'BlobCursor',
    displayName: 'Blob Cursor',
    slug: 'blob-cursor',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Custom blob cursor follower',
    icon: '🫧',
    tags: ['cursor', 'blob', 'follow', 'interactive'],
    componentPath: 'components/animations/transitions/BlobCursor.tsx',
    variantId: 1,
  },
  {
    name: 'ClickSpark',
    displayName: 'Click Spark',
    slug: 'click-spark',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Spark particles on click',
    icon: '✨',
    tags: ['click', 'spark', 'particles', 'interactive'],
    componentPath: 'components/animations/transitions/ClickSpark.tsx',
    variantId: 1,
  },
  {
    name: 'Crosshair',
    displayName: 'Crosshair Cursor',
    slug: 'crosshair',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Custom crosshair cursor',
    icon: '🎯',
    tags: ['cursor', 'crosshair', 'custom', 'interactive'],
    componentPath: 'components/animations/transitions/Crosshair.tsx',
    variantId: 1,
  },
  {
    name: 'Cubes',
    displayName: 'Cubes Transition',
    slug: 'cubes',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: '3D cubes transition effect',
    icon: '🎲',
    tags: ['transition', 'cubes', '3d', 'effect'],
    componentPath: 'components/animations/transitions/Cubes.tsx',
    variantId: 1,
  },
  {
    name: 'ElectricBorder',
    displayName: 'Electric Border',
    slug: 'electric-border',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Animated electric border effect',
    icon: '⚡',
    tags: ['border', 'electric', 'animation', 'effect'],
    componentPath: 'components/animations/transitions/ElectricBorder.tsx',
    variantId: 1,
  },
  {
    name: 'FadeContent',
    displayName: 'Fade Content',
    slug: 'fade-content',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Content with fade transitions',
    icon: '🌫️',
    tags: ['fade', 'transition', 'content', 'smooth'],
    componentPath: 'components/animations/transitions/FadeContent.tsx',
    variantId: 1,
  },
  {
    name: 'GlareHover',
    displayName: 'Glare Hover',
    slug: 'glare-hover',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Card with glare on hover',
    icon: '💿',
    tags: ['hover', 'glare', 'card', 'effect'],
    componentPath: 'components/animations/transitions/GlareHover.tsx',
    variantId: 1,
  },
  {
    name: 'GradualBlur',
    displayName: 'Gradual Blur',
    slug: 'gradual-blur',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Content with gradual blur effect',
    icon: '🌫️',
    tags: ['blur', 'gradual', 'transition', 'effect'],
    componentPath: 'components/animations/transitions/GradualBlur.tsx',
    variantId: 1,
  },
  {
    name: 'ImageTrail',
    displayName: 'Image Trail',
    slug: 'image-trail',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'gallery',
    description: 'Images following cursor trail',
    icon: '🖼️',
    tags: ['image', 'trail', 'cursor', 'follow'],
    componentPath: 'components/animations/transitions/ImageTrail.tsx',
    variantId: 1,
  },
  {
    name: 'LaserFlow',
    displayName: 'Laser Flow',
    slug: 'laser-flow',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Flowing laser border effect',
    icon: '🔦',
    tags: ['laser', 'flow', 'border', 'animation'],
    componentPath: 'components/animations/transitions/LaserFlow.tsx',
    variantId: 1,
  },
  {
    name: 'LogoLoop',
    displayName: 'Logo Loop',
    slug: 'logo-loop',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'logos',
    description: 'Infinite logo carousel loop',
    icon: '🔄',
    tags: ['logo', 'loop', 'carousel', 'infinite'],
    componentPath: 'components/animations/transitions/LogoLoop.tsx',
    variantId: 1,
  },
  {
    name: 'Magnet',
    displayName: 'Magnet Effect',
    slug: 'magnet',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Magnetic attraction hover effect',
    icon: '🧲',
    tags: ['magnet', 'hover', 'attraction', 'interactive'],
    componentPath: 'components/animations/transitions/Magnet.tsx',
    variantId: 1,
  },
  {
    name: 'MagnetLines',
    displayName: 'Magnet Lines',
    slug: 'magnet-lines',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Lines attracted to cursor like magnet',
    icon: '🧲',
    tags: ['magnet', 'lines', 'cursor', 'interactive'],
    componentPath: 'components/animations/transitions/MagnetLines.tsx',
    variantId: 1,
  },
  {
    name: 'MetaBalls',
    displayName: 'Meta Balls',
    slug: 'meta-balls',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Morphing meta balls effect',
    icon: '🫧',
    tags: ['metaballs', 'morph', 'blob', 'effect'],
    componentPath: 'components/animations/transitions/MetaBalls.tsx',
    variantId: 1,
  },
  {
    name: 'MetallicPaint',
    displayName: 'Metallic Paint',
    slug: 'metallic-paint',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Metallic paint brush effect',
    icon: '🎨',
    tags: ['metallic', 'paint', 'brush', 'effect'],
    componentPath: 'components/animations/transitions/MetallicPaint.tsx',
    variantId: 1,
  },
  {
    name: 'Noise',
    displayName: 'Noise Effect',
    slug: 'noise',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Animated noise texture overlay',
    icon: '📺',
    tags: ['noise', 'texture', 'overlay', 'animation'],
    componentPath: 'components/animations/transitions/Noise.tsx',
    variantId: 1,
  },
  {
    name: 'PixelTrail',
    displayName: 'Pixel Trail',
    slug: 'pixel-trail',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Pixelated cursor trail effect',
    icon: '🎮',
    tags: ['pixel', 'trail', 'cursor', 'retro'],
    componentPath: 'components/animations/transitions/PixelTrail.tsx',
    variantId: 1,
  },
  {
    name: 'PixelTransition',
    displayName: 'Pixel Transition',
    slug: 'pixel-transition',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Pixelated transition effect',
    icon: '🎮',
    tags: ['pixel', 'transition', 'retro', 'effect'],
    componentPath: 'components/animations/transitions/PixelTransition.tsx',
    variantId: 1,
  },
  {
    name: 'Ribbons',
    displayName: 'Ribbons',
    slug: 'ribbons',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Flowing ribbon animation',
    icon: '🎀',
    tags: ['ribbons', 'flow', 'animation', 'effect'],
    componentPath: 'components/animations/transitions/Ribbons.tsx',
    variantId: 1,
  },
  {
    name: 'ShapeBlur',
    displayName: 'Shape Blur',
    slug: 'shape-blur',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Shapes with blur transition',
    icon: '🔷',
    tags: ['shape', 'blur', 'transition', 'effect'],
    componentPath: 'components/animations/transitions/ShapeBlur.tsx',
    variantId: 1,
  },
  {
    name: 'SplashCursor',
    displayName: 'Splash Cursor',
    slug: 'splash-cursor',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Liquid splash cursor effect',
    icon: '💦',
    tags: ['cursor', 'splash', 'liquid', 'interactive'],
    componentPath: 'components/animations/transitions/SplashCursor.tsx',
    variantId: 1,
  },
  {
    name: 'StarBorder',
    displayName: 'Star Border',
    slug: 'star-border',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Animated star border effect',
    icon: '⭐',
    tags: ['border', 'star', 'animation', 'effect'],
    componentPath: 'components/animations/transitions/StarBorder.tsx',
    variantId: 1,
  },
  {
    name: 'StickerPeel',
    displayName: 'Sticker Peel',
    slug: 'sticker-peel',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Peeling sticker hover effect',
    icon: '🏷️',
    tags: ['sticker', 'peel', 'hover', 'effect'],
    componentPath: 'components/animations/transitions/StickerPeel.tsx',
    variantId: 1,
  },
  {
    name: 'TargetCursor',
    displayName: 'Target Cursor',
    slug: 'target-cursor',
    category: 'ANIMATIONS',
    subcategory: 'transitions',
    type: 'features',
    description: 'Target reticle cursor',
    icon: '🎯',
    tags: ['cursor', 'target', 'reticle', 'interactive'],
    componentPath: 'components/animations/transitions/TargetCursor.tsx',
    variantId: 1,
  },

  // UI Components (12)
  {
    name: 'Accordion',
    displayName: 'Accordion',
    slug: 'accordion',
    category: 'UI',
    subcategory: 'base',
    type: 'faq',
    description: 'Collapsible accordion component',
    icon: '📂',
    tags: ['accordion', 'collapse', 'faq', 'ui'],
    componentPath: 'components/ui/accordion.tsx',
    variantId: 1,
  },
  {
    name: 'Badge',
    displayName: 'Badge',
    slug: 'badge',
    category: 'UI',
    subcategory: 'base',
    type: 'features',
    description: 'Small badge component for labels',
    icon: '🏷️',
    tags: ['badge', 'label', 'tag', 'ui'],
    componentPath: 'components/ui/badge.tsx',
    variantId: 1,
  },
  {
    name: 'Button',
    displayName: 'Button',
    slug: 'button',
    category: 'UI',
    subcategory: 'base',
    type: 'cta',
    description: 'Interactive button component',
    icon: '🔘',
    tags: ['button', 'interactive', 'cta', 'ui'],
    componentPath: 'components/ui/button.tsx',
    variantId: 1,
  },
  {
    name: 'Card',
    displayName: 'Card',
    slug: 'card',
    category: 'UI',
    subcategory: 'base',
    type: 'features',
    description: 'Card container component',
    icon: '🎴',
    tags: ['card', 'container', 'layout', 'ui'],
    componentPath: 'components/ui/card.tsx',
    variantId: 1,
  },
  {
    name: 'Dialog',
    displayName: 'Dialog',
    slug: 'dialog',
    category: 'UI',
    subcategory: 'base',
    type: 'features',
    description: 'Modal dialog component',
    icon: '💬',
    tags: ['dialog', 'modal', 'popup', 'ui'],
    componentPath: 'components/ui/dialog.tsx',
    variantId: 1,
  },
  {
    name: 'DropdownMenu',
    displayName: 'Dropdown Menu',
    slug: 'dropdown-menu',
    category: 'UI',
    subcategory: 'base',
    type: 'header',
    description: 'Dropdown menu component',
    icon: '📝',
    tags: ['dropdown', 'menu', 'navigation', 'ui'],
    componentPath: 'components/ui/dropdown-menu.tsx',
    variantId: 1,
  },
  {
    name: 'Input',
    displayName: 'Input',
    slug: 'input',
    category: 'UI',
    subcategory: 'base',
    type: 'form',
    description: 'Text input field',
    icon: '✏️',
    tags: ['input', 'form', 'field', 'ui'],
    componentPath: 'components/ui/input.tsx',
    variantId: 1,
  },
  {
    name: 'Label',
    displayName: 'Label',
    slug: 'label',
    category: 'UI',
    subcategory: 'base',
    type: 'form',
    description: 'Form label component',
    icon: '🏷️',
    tags: ['label', 'form', 'text', 'ui'],
    componentPath: 'components/ui/label.tsx',
    variantId: 1,
  },
  {
    name: 'Separator',
    displayName: 'Separator',
    slug: 'separator',
    category: 'UI',
    subcategory: 'base',
    type: 'features',
    description: 'Visual separator line',
    icon: '—',
    tags: ['separator', 'divider', 'line', 'ui'],
    componentPath: 'components/ui/separator.tsx',
    variantId: 1,
  },
  {
    name: 'Tabs',
    displayName: 'Tabs',
    slug: 'tabs',
    category: 'UI',
    subcategory: 'base',
    type: 'features',
    description: 'Tabbed content component',
    icon: '📑',
    tags: ['tabs', 'navigation', 'content', 'ui'],
    componentPath: 'components/ui/tabs.tsx',
    variantId: 1,
  },
  {
    name: 'Textarea',
    displayName: 'Textarea',
    slug: 'textarea',
    category: 'UI',
    subcategory: 'base',
    type: 'form',
    description: 'Multi-line text input',
    icon: '📝',
    tags: ['textarea', 'input', 'form', 'ui'],
    componentPath: 'components/ui/textarea.tsx',
    variantId: 1,
  },
  {
    name: 'Tooltip',
    displayName: 'Tooltip',
    slug: 'tooltip',
    category: 'UI',
    subcategory: 'base',
    type: 'features',
    description: 'Hover tooltip component',
    icon: '💡',
    tags: ['tooltip', 'hover', 'help', 'ui'],
    componentPath: 'components/ui/tooltip.tsx',
    variantId: 1,
  },

  // SCRAM Components (renamed from Scram) - 11 components
  {
    name: 'Header1',
    displayName: 'Header Layout 1',
    slug: 'scram-header-1',
    category: 'SCRAM',
    subcategory: 'header',
    type: 'header',
    description: 'Simple header with logo and navigation',
    icon: '📱',
    tags: ['header', 'navigation', 'logo', 'simple'],
    componentPath: 'components/scram/header/Header1.tsx',
    variantId: 1,
  },
  {
    name: 'Header26',
    displayName: 'Header Layout 26',
    slug: 'scram-header-26',
    category: 'SCRAM',
    subcategory: 'header',
    type: 'header',
    description: 'Header with CTA button',
    icon: '📱',
    tags: ['header', 'navigation', 'cta', 'button'],
    componentPath: 'components/scram/header/Header26.tsx',
    variantId: 1,
  },
  {
    name: 'Header44',
    displayName: 'Header Layout 44',
    slug: 'scram-header-44',
    category: 'SCRAM',
    subcategory: 'header',
    type: 'header',
    description: 'Centered header layout',
    icon: '📱',
    tags: ['header', 'navigation', 'centered', 'logo'],
    componentPath: 'components/scram/header/Header44.tsx',
    variantId: 1,
  },
  {
    name: 'Header62',
    displayName: 'Header Layout 62',
    slug: 'scram-header-62',
    category: 'SCRAM',
    subcategory: 'header',
    type: 'header',
    description: 'Full-width header with search',
    icon: '📱',
    tags: ['header', 'navigation', 'search', 'fullwidth'],
    componentPath: 'components/scram/header/Header62.tsx',
    variantId: 1,
  },
  {
    name: 'Navbar1',
    displayName: 'Navbar Layout 1',
    slug: 'scram-navbar-1',
    category: 'SCRAM',
    subcategory: 'navbar',
    type: 'header',
    description: 'Basic navigation bar',
    icon: '🧭',
    tags: ['navbar', 'navigation', 'menu', 'basic'],
    componentPath: 'components/scram/navbar/Navbar1.tsx',
    variantId: 1,
  },
  {
    name: 'Navbar2',
    displayName: 'Navbar Layout 2',
    slug: 'scram-navbar-2',
    category: 'SCRAM',
    subcategory: 'navbar',
    type: 'header',
    description: 'Navbar with dropdown menus',
    icon: '🧭',
    tags: ['navbar', 'navigation', 'dropdown', 'menu'],
    componentPath: 'components/scram/navbar/Navbar2.tsx',
    variantId: 1,
  },
  {
    name: 'Navbar3',
    displayName: 'Navbar Layout 3',
    slug: 'scram-navbar-3',
    category: 'SCRAM',
    subcategory: 'navbar',
    type: 'header',
    description: 'Mobile-friendly navbar',
    icon: '🧭',
    tags: ['navbar', 'navigation', 'mobile', 'responsive'],
    componentPath: 'components/scram/navbar/Navbar3.tsx',
    variantId: 1,
  },
  {
    name: 'Footer1',
    displayName: 'Footer Layout 1',
    slug: 'scram-footer-1',
    category: 'SCRAM',
    subcategory: 'footer',
    type: 'footer',
    description: 'Multi-column footer with links',
    icon: '📄',
    tags: ['footer', 'links', 'columns', 'navigation'],
    componentPath: 'components/scram/footer/Footer1.tsx',
    variantId: 1,
  },
  {
    name: 'Footer3',
    displayName: 'Footer Layout 3',
    slug: 'scram-footer-3',
    category: 'SCRAM',
    subcategory: 'footer',
    type: 'footer',
    description: 'Simple footer with social links',
    icon: '📄',
    tags: ['footer', 'social', 'simple', 'links'],
    componentPath: 'components/scram/footer/Footer3.tsx',
    variantId: 1,
  },
  {
    name: 'CTA25',
    displayName: 'CTA Layout 25',
    slug: 'scram-cta-25',
    category: 'SCRAM',
    subcategory: 'cta',
    type: 'cta',
    description: 'Centered call-to-action section',
    icon: '📢',
    tags: ['cta', 'call-to-action', 'centered', 'button'],
    componentPath: 'components/scram/cta/CTA25.tsx',
    variantId: 1,
  },
  {
    name: 'CTA8',
    displayName: 'CTA Layout 8',
    slug: 'scram-cta-8',
    category: 'SCRAM',
    subcategory: 'cta',
    type: 'cta',
    description: 'Split CTA with image',
    icon: '📢',
    tags: ['cta', 'call-to-action', 'split', 'image'],
    componentPath: 'components/scram/cta/CTA8.tsx',
    variantId: 1,
  },

  // ADVANCED Components (8)
  {
    name: 'ProgressBar',
    displayName: 'Progress Bar',
    slug: 'progress-bar',
    category: 'ADVANCED',
    subcategory: 'feedback',
    type: 'features',
    description: 'Progress indicator bar',
    icon: '📊',
    tags: ['progress', 'loading', 'indicator', 'bar'],
    componentPath: 'components/advanced/feedback/ProgressBar.tsx',
    variantId: 1,
  },
  {
    name: 'Skeleton',
    displayName: 'Skeleton Loader',
    slug: 'skeleton',
    category: 'ADVANCED',
    subcategory: 'feedback',
    type: 'features',
    description: 'Loading skeleton placeholder',
    icon: '💀',
    tags: ['skeleton', 'loading', 'placeholder', 'shimmer'],
    componentPath: 'components/advanced/feedback/Skeleton.tsx',
    variantId: 1,
  },
  {
    name: 'Toast',
    displayName: 'Toast Notification',
    slug: 'toast',
    category: 'ADVANCED',
    subcategory: 'feedback',
    type: 'features',
    description: 'Toast notification component',
    icon: '🍞',
    tags: ['toast', 'notification', 'alert', 'message'],
    componentPath: 'components/advanced/feedback/Toast.tsx',
    variantId: 1,
  },
  {
    name: 'FileUpload',
    displayName: 'File Upload',
    slug: 'file-upload',
    category: 'ADVANCED',
    subcategory: 'forms',
    type: 'form',
    description: 'Drag and drop file upload',
    icon: '📤',
    tags: ['upload', 'file', 'drag', 'drop'],
    componentPath: 'components/advanced/forms/FileUpload.tsx',
    variantId: 1,
  },
  {
    name: 'InputOTP',
    displayName: 'OTP Input',
    slug: 'input-otp',
    category: 'ADVANCED',
    subcategory: 'forms',
    type: 'form',
    description: 'One-time password input field',
    icon: '🔢',
    tags: ['otp', 'input', 'code', 'verification'],
    componentPath: 'components/advanced/forms/InputOTP.tsx',
    variantId: 1,
  },
  {
    name: 'SearchInput',
    displayName: 'Search Input',
    slug: 'search-input',
    category: 'ADVANCED',
    subcategory: 'forms',
    type: 'form',
    description: 'Search input with autocomplete',
    icon: '🔍',
    tags: ['search', 'input', 'autocomplete', 'find'],
    componentPath: 'components/advanced/forms/SearchInput.tsx',
    variantId: 1,
  },
  {
    name: 'Container',
    displayName: 'Container',
    slug: 'container',
    category: 'ADVANCED',
    subcategory: 'layout',
    type: 'features',
    description: 'Responsive container component',
    icon: '📦',
    tags: ['container', 'layout', 'wrapper', 'responsive'],
    componentPath: 'components/advanced/layout/Container.tsx',
    variantId: 1,
  },
  {
    name: 'EmptyState',
    displayName: 'Empty State',
    slug: 'empty-state',
    category: 'ADVANCED',
    subcategory: 'layout',
    type: 'features',
    description: 'Empty state placeholder',
    icon: '🗂️',
    tags: ['empty', 'placeholder', 'state', 'no-data'],
    componentPath: 'components/advanced/layout/EmptyState.tsx',
    variantId: 1,
  },

  // EFFECTS Components (7)
  {
    name: 'DotPattern',
    displayName: 'Dot Pattern',
    slug: 'dot-pattern',
    category: 'EFFECTS',
    subcategory: 'background',
    type: 'background',
    description: 'Static dot pattern background',
    icon: '⋮',
    tags: ['pattern', 'dots', 'background', 'effect'],
    componentPath: 'components/effects/background/DotPattern.tsx',
    variantId: 1,
  },
  {
    name: 'GridPattern',
    displayName: 'Grid Pattern',
    slug: 'grid-pattern',
    category: 'EFFECTS',
    subcategory: 'background',
    type: 'background',
    description: 'Static grid pattern background',
    icon: '📐',
    tags: ['pattern', 'grid', 'background', 'effect'],
    componentPath: 'components/effects/background/GridPattern.tsx',
    variantId: 1,
  },
  {
    name: 'Meteors',
    displayName: 'Meteors',
    slug: 'meteors',
    category: 'EFFECTS',
    subcategory: 'background',
    type: 'background',
    description: 'Falling meteors background effect',
    icon: '☄️',
    tags: ['meteors', 'falling', 'background', 'effect'],
    componentPath: 'components/effects/background/Meteors.tsx',
    variantId: 1,
  },
  {
    name: 'AnimatedGradientText',
    displayName: 'Animated Gradient Text',
    slug: 'animated-gradient-text',
    category: 'EFFECTS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with animated gradient',
    icon: '🌈',
    tags: ['text', 'gradient', 'animated', 'effect'],
    componentPath: 'components/effects/text/AnimatedGradientText.tsx',
    variantId: 1,
  },
  {
    name: 'FlipText',
    displayName: 'Flip Text',
    slug: 'flip-text',
    category: 'EFFECTS',
    subcategory: 'text',
    type: 'hero',
    description: 'Text with flip animation',
    icon: '🔄',
    tags: ['text', 'flip', 'animation', 'effect'],
    componentPath: 'components/effects/text/FlipText.tsx',
    variantId: 1,
  },
  {
    name: 'ShimmerButton',
    displayName: 'Shimmer Button',
    slug: 'shimmer-button',
    category: 'EFFECTS',
    subcategory: 'text',
    type: 'cta',
    description: 'Button with shimmer effect',
    icon: '✨',
    tags: ['button', 'shimmer', 'effect', 'cta'],
    componentPath: 'components/effects/text/ShimmerButton.tsx',
    variantId: 1,
  },
  {
    name: 'TypingAnimation',
    displayName: 'Typing Animation',
    slug: 'typing-animation',
    category: 'EFFECTS',
    subcategory: 'text',
    type: 'hero',
    description: 'Simple typing text animation',
    icon: '⌨️',
    tags: ['text', 'typing', 'animation', 'typewriter'],
    componentPath: 'components/effects/text/TypingAnimation.tsx',
    variantId: 1,
  },

  // BUILDER Components (6)
  {
    name: 'BuilderView',
    displayName: 'Builder View',
    slug: 'builder-view',
    category: 'BUILDER',
    subcategory: 'main',
    type: 'features',
    description: 'Main builder interface view',
    icon: '🏗️',
    tags: ['builder', 'view', 'interface', 'main'],
    componentPath: 'app/dashboard/builder/components/BuilderView.tsx',
    variantId: 1,
  },
  {
    name: 'DesignView',
    displayName: 'Design View',
    slug: 'design-view',
    category: 'BUILDER',
    subcategory: 'main',
    type: 'features',
    description: 'Design editor view',
    icon: '🎨',
    tags: ['design', 'view', 'editor', 'interface'],
    componentPath: 'app/dashboard/builder/components/DesignView.tsx',
    variantId: 1,
  },
  {
    name: 'LandingPageBuilder',
    displayName: 'Landing Page Builder',
    slug: 'landing-page-builder',
    category: 'BUILDER',
    subcategory: 'main',
    type: 'features',
    description: 'Landing page builder interface',
    icon: '🚀',
    tags: ['landing', 'builder', 'page', 'interface'],
    componentPath: 'app/dashboard/builder/components/LandingPageBuilder.tsx',
    variantId: 1,
  },
  {
    name: 'StyleGuideView',
    displayName: 'Style Guide View',
    slug: 'style-guide-view',
    category: 'BUILDER',
    subcategory: 'main',
    type: 'features',
    description: 'Style guide editor view',
    icon: '🎨',
    tags: ['style', 'guide', 'view', 'editor'],
    componentPath: 'app/dashboard/builder/components/StyleGuideView.tsx',
    variantId: 1,
  },
  {
    name: 'WireframeMockups',
    displayName: 'Wireframe Mockups',
    slug: 'wireframe-mockups',
    category: 'BUILDER',
    subcategory: 'main',
    type: 'features',
    description: 'Wireframe mockup components',
    icon: '📐',
    tags: ['wireframe', 'mockup', 'preview', 'builder'],
    componentPath: 'app/dashboard/builder/components/WireframeMockups.tsx',
    variantId: 1,
  },
  {
    name: 'WireframeView',
    displayName: 'Wireframe View',
    slug: 'wireframe-view',
    category: 'BUILDER',
    subcategory: 'main',
    type: 'features',
    description: 'Wireframe editor view',
    icon: '📋',
    tags: ['wireframe', 'view', 'editor', 'builder'],
    componentPath: 'app/dashboard/builder/components/WireframeView.tsx',
    variantId: 1,
  },

  // PROVIDERS Component (1)
  {
    name: 'SessionProvider',
    displayName: 'Session Provider',
    slug: 'session-provider',
    category: 'PROVIDERS',
    subcategory: 'auth',
    type: 'features',
    description: 'Authentication session provider',
    icon: '🔐',
    tags: ['session', 'auth', 'provider', 'context'],
    componentPath: 'components/providers/session-provider.tsx',
    variantId: 1,
  },
]
